stages:
  - build
  - release

jdk8:
  stage: build
  image: java:8
  script: ./gradlew build -i -s
  artifacts:
    paths:
    - build/reports
    expire_in: 1 week
  cache:
    paths:
    - $HOME/.gradle
    - build/terraform-binaries
  except:
  - pages

publish:
  stage: release
  image: java:8
  script: ./gradlew installDocs publishPlugins gitPublishPush -i -Dgradle.publish.key=$GRADLE_PORTAL_KEY -Dgradle.publish.secret=$GRADLE_PORTAL_SECRET -Dorg.ajoberstar.grgit.auth.username=$PAGES_PUBLISH_USER -Dorg.ajoberstar.grgit.auth.password=$PAGES_PUBLISH_KEY -Dorg.ajoberstar.grgit.auth.force=hardcoded
  dependencies:
  - jdk8
  only:
  - release

pages:
  stage: release
  script: ls -la
  artifacts:
    paths:
    - public
  only:
  - pages

