---
name: CI

on:
    push:
        branches:
            - '*'

jobs:
    build:
        strategy:
            matrix:
                java: [21, 17]
        runs-on: ubuntu-latest
        env:
            GH_USERNAME: ${{ secrets.GH_USERNAME }}
            GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
        steps:
            - uses: actions/checkout@v4.1.7
            - name: Set up JDK ${{ matrix.java }}
              uses: actions/setup-java@v4.2.2
              with:
                  java-version: ${{ matrix.java }}
                  distribution: 'adopt'
            - name: Cache Gradle Caches
              uses: gradle/actions/setup-gradle@v3.3.1

            - name: Build with Gradle
              run: |
                  ./gradlew -i -s check test assemble

            - name: Publish Plugin to github if main branch
              run: |
                  if [ "${{ matrix.java }}" == "21" ]; then
                    ./gradlew publishAllPublicationsToGithubPackagesRepository --stacktrace
                  fi
              if: success() && github.event_name == 'push' && github.ref == 'refs/heads/master'
