---
name: CI

on:
    push:
        branches:
            - '*'
        tags-ignore:
            - '*'
    pull_request:
        branches:
            - '*'

jobs:
    build:
        strategy:
            matrix:
                java: [8, 11]
        runs-on: ubuntu-latest
        env:
            GH_USERNAME: ${{ secrets.GH_USERNAME }}
            GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
        steps:
            - uses: actions/checkout@v4.1.7
            - name: Set up JDK ${{ matrix.java }}
              uses: actions/setup-java@v4.2.2
              with:
                  java-version: ${{ matrix.java }}
                  distribution: 'adopt'
            - name: Cache Gradle packages
              uses: actions/cache@v4.0.2
              with:
                  path: ~/.gradle/caches
                  key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
                  restore-keys: ${{ runner.os }}-gradle
            - name: Build with Gradle
              run: |
                  if [ "${{ matrix.java }}" == "8" ]; then
                    ./gradlew build -i -s -x gradleTest
                  else
                    ./gradlew -i -s assemble
                  fi
            - name: Run compatibility test
              run: ./run-compatibility-test-on-ci.sh
              env:
                  GRADLE_VERSIONS: '7.0.2,7.6.1' # ['6.0,6.3,6.8.1', '7.0.2,7.6.1', '8.0.2,8.1.1']

            - name: Publish Plugin to github if main branch
              run: |
                  if [ "${{ matrix.java }}" == "11" ]; then
                    ./gradlew publishAllPublicationsToGithubPackagesRepository
                  fi
              if: success() && github.event_name == 'push' && github.ref == 'refs/heads/master'
